[project]
name = "ryzor"
version = "0.2.5"
description = "CLI para organização de arquivos"
authors = [{ name = "Lucas Paulino Da Silva", email = "lucas.workps@gmail.com" }]
dependencies = ["rich", "pyfiglet", "send2trash"]

[project.scripts]
ryzor = "cli:main"